debug: true
language: ruby
cache: bundler
rvm:
- 1.9.3
before_install:
- gem --version
before_script:
script:
- bundle exec rake spec
addons:
  code_climate:
    repo_token: "Opc0FW8gjJzf0EONWVZb7awIB+RMa3RNmXtxt+gJVwOv7aTvpcub6lFoK9SHykD1N1SdZwCjto1AuEKZmXHkwSjyOOjgZC7rtQzkg5zg+J4gqOs/bQrA6CqdGhgMpCscqUI8O5MPTHDNlOWaKASaGjMokv1H5FdoLCdc1OZId7U="
notifications:
  email: false
